In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"F:\FINAL\DL_FINAL\after_merged.csv")
df


Unnamed: 0  aisle_id                       aisle  product_id  \
0                  0         1       prepared soups salads         209   
1                  1         1       prepared soups salads         209   
2                  2         1       prepared soups salads         209   
3                  3         1       prepared soups salads         209   
4                  4         1       prepared soups salads         209   
...              ...       ...                         ...         ...   
33819101    33819101       134  specialty wines champagnes       49661   
33819102    33819102       134  specialty wines champagnes       49661   
33819103    33819103       134  specialty wines champagnes       49661   
33819104    33819104       134  specialty wines champagnes       49661   
33819105    33819105       134  specialty wines champagnes       49661   

                 product_name  department_id department  order_id  \
0         Italian Pasta Salad             20       deli     94246   
1         Italian Pasta Salad             20       deli    192465   
2         Italian Pasta Salad             20       deli    195206   
3         Italian Pasta Salad             20       deli    227717   
4         Italian Pasta Salad             20       deli    260072   
...                       ...            ...        ...       ...   
33819101                Porto              5    alcohol   2238789   
33819102                Porto              5    alcohol   2251344   
33819103                Porto              5    alcohol   2616249   
33819104                Porto              5    alcohol   2715237   
33819105                Porto              5    alcohol   3263901   

          add_to_cart_order  reordered  user_id eval_set  order_number  \
0                         5          0   114082    prior            26   
1                         2          1   119977    prior             2   
2                        18          1     1519    prior             7   
3                         1          1   161125    prior             7   
4                        13          0    12012    prior             5   
...                     ...        ...      ...      ...           ...   
33819101                 10          1    72244    prior            19   
33819102                  5          1    72244    prior            18   
33819103                  2          0   100075    prior             8   
33819104                  1          0   135045    prior             3   
33819105                  6          1    72244    prior            15   

          order_dow  order_hour_of_day  days_since_prior_order  
0                 0                 20                     1.0  
1                 0                 16                     3.0  
2                 2                  9                     5.0  
3                 2                 11                    11.0  
4                 5                 11                    11.0  
...             ...                ...                     ...  
33819101          4                 23                     5.0  
33819102          6                 10                     9.0  
33819103          4                 17                     9.0  
33819104          6                 14                    30.0  
33819105          4                  9                    14.0  

[33819106 rows x 16 columns]

In [3]:
df.columns

Index(['Unnamed: 0', 'aisle_id', 'aisle', 'product_id', 'product_name',
       'department_id', 'department', 'order_id', 'add_to_cart_order',
       'reordered', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

In [4]:
df['Unnamed: 0']

0                  0
1                  1
2                  2
3                  3
4                  4
              ...   
33819101    33819101
33819102    33819102
33819103    33819103
33819104    33819104
33819105    33819105
Name: Unnamed: 0, Length: 33819106, dtype: int64

In [5]:
df.drop(columns = ["Unnamed: 0"], axis=1, inplace = True) # dropping  column unnamed

In [6]:
df

aisle_id                       aisle  product_id  \
0                1       prepared soups salads         209   
1                1       prepared soups salads         209   
2                1       prepared soups salads         209   
3                1       prepared soups salads         209   
4                1       prepared soups salads         209   
...            ...                         ...         ...   
33819101       134  specialty wines champagnes       49661   
33819102       134  specialty wines champagnes       49661   
33819103       134  specialty wines champagnes       49661   
33819104       134  specialty wines champagnes       49661   
33819105       134  specialty wines champagnes       49661   

                 product_name  department_id department  order_id  \
0         Italian Pasta Salad             20       deli     94246   
1         Italian Pasta Salad             20       deli    192465   
2         Italian Pasta Salad             20       deli    195206   
3         Italian Pasta Salad             20       deli    227717   
4         Italian Pasta Salad             20       deli    260072   
...                       ...            ...        ...       ...   
33819101                Porto              5    alcohol   2238789   
33819102                Porto              5    alcohol   2251344   
33819103                Porto              5    alcohol   2616249   
33819104                Porto              5    alcohol   2715237   
33819105                Porto              5    alcohol   3263901   

          add_to_cart_order  reordered  user_id eval_set  order_number  \
0                         5          0   114082    prior            26   
1                         2          1   119977    prior             2   
2                        18          1     1519    prior             7   
3                         1          1   161125    prior             7   
4                        13          0    12012    prior             5   
...                     ...        ...      ...      ...           ...   
33819101                 10          1    72244    prior            19   
33819102                  5          1    72244    prior            18   
33819103                  2          0   100075    prior             8   
33819104                  1          0   135045    prior             3   
33819105                  6          1    72244    prior            15   

          order_dow  order_hour_of_day  days_since_prior_order  
0                 0                 20                     1.0  
1                 0                 16                     3.0  
2                 2                  9                     5.0  
3                 2                 11                    11.0  
4                 5                 11                    11.0  
...             ...                ...                     ...  
33819101          4                 23                     5.0  
33819102          6                 10                     9.0  
33819103          4                 17                     9.0  
33819104          6                 14                    30.0  
33819105          4                  9                    14.0  

[33819106 rows x 15 columns]

In [7]:
df["aisle_id"].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134])

In [8]:
df["aisle"].unique()

array(['prepared soups salads', 'specialty cheeses',
       'energy granola bars', 'instant foods',
       'marinades meat preparation', 'other', 'packaged meat',
       'bakery desserts', 'pasta sauce', 'kitchen supplies',
       'cold flu allergy', 'fresh pasta', 'prepared meals',
       'tofu meat alternatives', 'packaged seafood', 'fresh herbs',
       'baking ingredients', 'bulk dried fruits vegetables',
       'oils vinegars', 'oral hygiene', 'packaged cheese', 'hair care',
       'popcorn jerky', 'fresh fruits', 'soap', 'coffee', 'beers coolers',
       'red wines', 'honeys syrups nectars', 'latino foods',
       'refrigerated', 'packaged produce', 'kosher foods',
       'frozen meat seafood', 'poultry counter', 'butter',
       'ice cream ice', 'frozen meals', 'seafood counter',
       'dog food care', 'cat food care', 'frozen vegan vegetarian',
       'buns rolls', 'eye ear care', 'candy chocolate', 'mint gum',
       'vitamins supplements', 'breakfast bars pastries',
       '

In [9]:
df["product_id"].unique()

array([  209,   554,   886, ..., 49438, 49562, 49661], shape=(49685,))

In [10]:
df['product_name'].unique()

array(['Italian Pasta Salad', 'Turkey Chili',
       'Whole Grain Salad with Roasted Pecans & Mango Vinaigrette', ...,
       'Dry Fino Sherry', 'Blanc De Noirs Sparkling Wine', 'Porto'],
      shape=(49685,), dtype=object)

In [11]:
df['department_id'].unique()

array([20, 16, 19,  9, 13,  2, 12,  3, 17, 11,  4, 10,  7,  5,  6,  1,  8,
       14, 18, 15, 21])

In [12]:
df['department'].unique()

array(['deli', 'dairy eggs', 'snacks', 'dry goods pasta', 'pantry',
       'other', 'meat seafood', 'bakery', 'household', 'personal care',
       'produce', 'bulk', 'beverages', 'alcohol', 'international',
       'frozen', 'pets', 'breakfast', 'babies', 'canned goods', 'missing'],
      dtype=object)

In [13]:
df['order_id'].unique()


array([  94246,  192465,  195206, ...,  250923, 1319402, 2298986],
      shape=(3346083,))

In [14]:
df['add_to_cart_order'].unique()

array([  5,   2,  18,   1,  13,   4,   7,  10,  11,   3,  14,  12,   9,
        25,  16,  15,  17,  27,   6,   8,  22,  21,  24,  28,  23,  37,
        20,  38,  19,  33,  29,  30,  46,  35,  32,  26,  50,  31,  40,
        34,  42,  48,  36,  44,  39,  45,  41,  49,  60,  47,  63,  55,
        57,  54,  52,  43,  58,  68,  56,  62,  51,  65,  53,  61,  64,
        75,  67,  92,  59,  87,  90,  66,  78,  70,  76,  73,  71,  74,
        72,  69,  82,  79,  80,  96,  95,  91,  83,  77,  86, 101,  97,
        98,  85,  88,  84, 103,  81, 100, 127,  99, 104,  89, 102, 134,
       107, 144,  93,  94, 142, 110, 111, 128, 114, 123, 119, 120, 105,
       112, 143, 113, 137, 129, 115, 132, 116, 108, 145, 135, 106, 130,
       109, 124, 125, 122, 117, 121, 118, 136, 131, 133, 138, 126, 140,
       139, 141])

In [15]:
df['reordered'].unique()

array([0, 1])

In [16]:
df['user_id'].unique()

array([114082, 119977,   1519, ...,  47381, 118411,  95228],
      shape=(206209,))

In [17]:
df['eval_set'].unique()

array(['prior', 'train'], dtype=object)

In [18]:
df['order_number'].unique()

array([ 26,   2,   7,   5,   4,  36,   9,   8,   3,   6,  33,   1,  30,
        51,  14,  20,  45,  19,  24,  12,  47,  32,  13,  15,  10,  11,
        46,  22,  27,  16,  58,  31,  18,  88,  39,  34,  61,  21,  52,
        70,  38,  35,  73,  29,  28,  50,  55,  54,  37,  53,  25,  42,
        99,  23,  49,  40,  41,  17,  44,  43,  66,  56,  48,  62,  60,
        72,  68,  79,  86,  90,  75,  57,  64,  71,  59,  78,  65,  69,
        63,  74,  89,  76,  67,  83,  77,  87,  81,  85,  82,  95,  91,
        80,  93,  97,  98,  94,  92,  96,  84, 100])

In [19]:
df['order_dow'].unique()

array([0, 2, 5, 1, 3, 6, 4])

In [20]:
df['order_hour_of_day'].unique()

array([20, 16,  9, 11, 10, 12, 17, 14,  8, 22, 18, 13,  7, 15, 19, 23, 21,
        1,  2,  5,  0,  4,  6,  3])

In [21]:
df['days_since_prior_order'].unique()

array([ 1.,  3.,  5., 11.,  8.,  9., 18.,  7., 13., 30.,  0., nan,  4.,
       24., 14., 28.,  2.,  6., 21., 20., 12., 10., 17., 27., 16., 15.,
       23., 19., 25., 29., 22., 26.])

In [22]:
df.shape #count of rows and columns

(33819106, 15)

In [23]:
df.isnull().values.any()  #checking null values 

np.True_

In [24]:
df.isnull().sum().sum()

np.int64(2078068)

In [25]:
 #checking null and its sum
df.isnull().sum()

aisle_id                        0
aisle                           0
product_id                      0
product_name                    0
department_id                   0
department                      0
order_id                        0
add_to_cart_order               0
reordered                       0
user_id                         0
eval_set                        0
order_number                    0
order_dow                       0
order_hour_of_day               0
days_since_prior_order    2078068
dtype: int64

In [26]:
df.dtypes  #Checking datatypes

aisle_id                    int64
aisle                      object
product_id                  int64
product_name               object
department_id               int64
department                 object
order_id                    int64
add_to_cart_order           int64
reordered                   int64
user_id                     int64
eval_set                   object
order_number                int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [ ]:
df[df.duplicated()].sum()  #checking duplicates and its sum

aisle_id                    0
aisle                       0
product_id                  0
product_name                0
department_id               0
department                  0
order_id                    0
add_to_cart_order           0
reordered                   0
user_id                     0
eval_set                    0
order_number                0
order_dow                   0
order_hour_of_day           0
days_since_prior_order    0.0
dtype: object

In [28]:
df[df.isnull().any(axis=1)]

aisle_id                       aisle  product_id  \
16               1       prepared soups salads         209   
18               1       prepared soups salads         209   
19               1       prepared soups salads         209   
24               1       prepared soups salads         209   
37               1       prepared soups salads         209   
...            ...                         ...         ...   
33819045       134  specialty wines champagnes       48984   
33819062       134  specialty wines champagnes       48984   
33819064       134  specialty wines champagnes       49438   
33819073       134  specialty wines champagnes       49438   
33819091       134  specialty wines champagnes       49562   

                           product_name  department_id department  order_id  \
16                  Italian Pasta Salad             20       deli    686260   
18                  Italian Pasta Salad             20       deli    836624   
19                  Italian Pasta Salad             20       deli    909037   
24                  Italian Pasta Salad             20       deli   1134475   
37                  Italian Pasta Salad             20       deli   1714420   
...                                 ...            ...        ...       ...   
33819045                     Dry Sherry              5    alcohol   2599188   
33819062                     Dry Sherry              5    alcohol   3357995   
33819064                Dry Fino Sherry              5    alcohol    256365   
33819073                Dry Fino Sherry              5    alcohol   1883416   
33819091  Blanc De Noirs Sparkling Wine              5    alcohol   2715417   

          add_to_cart_order  reordered  user_id eval_set  order_number  \
16                        1          0    32209    prior             1   
18                        2          0   119977    prior             1   
19                        2          0    46519    prior             1   
24                        1          0   120530    prior             1   
37                        3          0    12605    prior             1   
...                     ...        ...      ...      ...           ...   
33819045                  3          0   187048    prior             1   
33819062                 31          0   175547    prior             1   
33819064                  6          0    62858    prior             1   
33819073                  6          0   138795    prior             1   
33819091                  6          0    56858    prior             1   

          order_dow  order_hour_of_day  days_since_prior_order  
16                2                 18                     NaN  
18                4                 10                     NaN  
19                6                 17                     NaN  
24                6                 13                     NaN  
37                2                 10                     NaN  
...             ...                ...                     ...  
33819045          4                 14                     NaN  
33819062          0                 13                     NaN  
33819064          3                 18                     NaN  
33819073          0                 12                     NaN  
33819091          5                 15                     NaN  

[2078068 rows x 15 columns]

In [29]:
df1 = df.copy()

In [30]:
df1['days_since_prior_order'].isna().sum()

np.int64(2078068)

In [ ]:
df1['days_since_prior_order'].value_counts(dropna=False)    #df1['days_since_prior_order'] - Selects the column named days_since_prior_order.
                                                            #.value_counts
                                                            # Counts how many times each unique value appears in that column.
                                                            #dropna=False means it includes NaN values in the count (by default, .value_counts() drops NaNs).

days_since_prior_order
7.0     3586305
30.0    3477322
6.0     2592077
5.0     2180537
4.0     2126287
NaN     2078068
8.0     1995636
3.0     1914431
2.0     1492379
9.0     1262383
14.0    1082295
10.0    1003366
1.0      960381
13.0     890959
11.0     854391
12.0     808260
15.0     705361
16.0     485824
21.0     473730
0.0      465742
20.0     404037
17.0     403367
18.0     371041
19.0     355803
22.0     329575
28.0     274572
23.0     241605
27.0     219711
24.0     207537
25.0     194638
29.0     191037
26.0     190449
Name: count, dtype: int64

In [ ]:
numerical_cols = df1.select_dtypes(['int64', 'float64']).columns   #df1.select_dtypes(['int64', 'float64'])
                                                                   #Selects only the columns in df that are of data types int64 or float64 (i.e., numeric columns).
                                                                   #.columns -Retrieves the column names (i.e., the labels of the selected numeric columns).
numerical_cols

Index(['aisle_id', 'product_id', 'department_id', 'order_id',
       'add_to_cart_order', 'reordered', 'user_id', 'order_number',
       'order_dow', 'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

In [ ]:
for i in numerical_cols:                            # Loop through each column in numerical_cols:i takes the name of each numerical column one by one.
    corr = df1['days_since_prior_order'].corr(df1[i]) #Calculate correlation: computes the Pearson correlation coefficient between the 'days_since_prior_order' column and column i.
                                                     #Pearson correlation is a measure of the linear relationship between two continuous variables.
df1['days_since_prior_order'].corr(df1[i])           # It ranges from -1 (perfect negative correlation) to 1 (perfect positive correlation), with 0 meaning no linear correlation.
print(f'corr{i} :', corr)

corraisle_id : 0.005974780321816446
corrproduct_id : 0.0007683932256555329
corrdepartment_id : 0.0004157695568837211
corrorder_id : 0.0006952893165710942
corradd_to_cart_order : 0.053056055599938354
corrreordered : -0.13470761641075435
corruser_id : 0.0008022947467892665
corrorder_number : -0.3586361614811619
corrorder_dow : -0.030062355296774954
corrorder_hour_of_day : 0.004995255349715148
corrdays_since_prior_order : 0.9999999999999998


MULTIPLE IMPUTATION BY CHAINED EQUATIONS TO FILL MISSING VALUES IN VALUE CONFIGURATION

In [ ]:
#need to enable iterative imputer explicity since its still experimental
from sklearn.experimental import enable_iterative_imputer    # Enables use of IterativeImputer
from sklearn.impute import IterativeImputer                   # Import the actual imputer

In [ ]:
# What is MICE?
#MICE is a sophisticated multivariate imputation method that:
#Fills in missing values iteratively, using regression models based on other features.
#Performs better than simple imputation methods like mean, median, or mode when data is not missing completely at random.
#How it works:
#Each feature with missing values is regressed on other features.
#Missing values are predicted based on this regression.
#This is repeated in a round-robin fashion until convergence.
#This results in more statistically sound imputations, especially for complex datasets.

In [ ]:
#The IterativeImputer is still considered experimental in scikit-learn (even in newer versions), so to use it, you must explicitly enable it.
#Without the first line, you'll get an ImportError.

In [ ]:
| Use Case                            | Why MICE Helps                                              |
| ----------------------------------- | ----------------------------------------------------------- |
| Missing values in multiple features | Uses correlations between features to fill in intelligently |
| Time-series or correlated variables | Preserves dependencies across columns                       |
| Complex, non-linear relationships   | Better than mean/median imputation                          |
| Want better model performance       | Imputed data is more realistic, so models generalize better |


In [35]:
#Define Imputer
imputer = IterativeImputer(random_state = 100, max_iter=10)

In [ ]:
#IterativeImputer(...)
#This uses Multiple Imputation by Chained Equations (MICE) to estimate missing values.
#Parameters:random_state=100
#Ensures reproducibility of results.
#Controls the randomness involved in imputation.
#Same input will always give the same output if you reuse this random_state.
#max_iter=10 = Number of maximum iterations the imputer will run to refine the imputed values.
#In each iteration, the imputer updates its guesses of the missing values.
#10 is usually a good default for convergence.

#When a column (say, A) has missing values, IterativeImputer treats A as the target variable, and the rest of the columns (B, C, etc.) 
#as the predictor variables (features). It trains a regression model using the available (non-missing) data and uses that model to predict the missing values 
#in A."""

In [ ]:
df1_train = df1.loc[:,['reordered','order_dow', 'order_hour_of_day' ,'days_since_prior_order']]   # df1.loc[:, [...]]
                                                                                                 #This uses the .loc[] accessor to select specific columns from the DataFrame df1.
                                                                                                 # : means select all rows.
#['reordered', 'order_dow', 'order_hour_of_day', 'days_since_prior_order'] specifies the subset of columns to include.
                                                                                                    #.sample(3)
                                                                                                    # This returns 3 random rows from df1_train.
                                                                                                    # Used for quick inspection or debugging to see sample values.
df1_train.sample(3)                                                                          # The result is stored in a new DataFrame df1_train.

reordered  order_dow  order_hour_of_day  days_since_prior_order
23961624          0          1                 18                    19.0
2200188           1          1                 19                     4.0
22831920          1          1                  9                     4.0

In [37]:
df1_train['days_since_prior_order'].value_counts(dropna=False)

days_since_prior_order
7.0     3586305
30.0    3477322
6.0     2592077
5.0     2180537
4.0     2126287
NaN     2078068
8.0     1995636
3.0     1914431
2.0     1492379
9.0     1262383
14.0    1082295
10.0    1003366
1.0      960381
13.0     890959
11.0     854391
12.0     808260
15.0     705361
16.0     485824
21.0     473730
0.0      465742
20.0     404037
17.0     403367
18.0     371041
19.0     355803
22.0     329575
28.0     274572
23.0     241605
27.0     219711
24.0     207537
25.0     194638
29.0     191037
26.0     190449
Name: count, dtype: int64

In [ ]:
#fit on the dataset           Step 1: imputer.fit(df1_train)
                            #The IterativeImputer learns the relationships between the columns in df1_train.
                            #It analyzes observed data to build regression models that will be used to predict
                            # missing values for columns that have any missing data.
imputer.fit(df1_train)

IterativeImputer(random_state=100)

In [ ]:
df_imputed = imputer.transform(df1_train)   #Step 2: df_imputed = imputer.transform(df1_train)
                                            #Now that the imputer has learned the data patterns, .transform() 
                                           #fills the missing values in df1_train using those learned regression models.
                                           #It returns a NumPy array (df_imputed) where all missing values are replaced by the imputed estimates.
                                           #The array has the same shape as df1_train.
df_imputed[:10]

array([[ 0.,  0., 20.,  1.],
       [ 1.,  0., 16.,  3.],
       [ 1.,  2.,  9.,  5.],
       [ 1.,  2., 11., 11.],
       [ 0.,  5., 11., 11.],
       [ 1.,  2., 10.,  5.],
       [ 1.,  1., 12.,  8.],
       [ 0.,  1., 10.,  9.],
       [ 0.,  3., 12., 18.],
       [ 0.,  5., 17.,  1.]])

In [ ]:
df.loc[:, ['reordered','order_dow', 'order_hour_of_day' ,'days_since_prior_order']] = df_imputed  

#This updates the original DataFrame df for the specified columns with the imputed values.
#Since df_imputed is a NumPy array and df.loc[...] selects those columns, 
#this line replaces the original columns (which may have missing values) with the fully imputed data.
#After this step, df no longer has missing values in these columns (assuming imputer filled them all).


In [41]:
df['days_since_prior_order'].value_counts(dropna=False)

days_since_prior_order
7.000000     3586305
30.000000    3477322
6.000000     2592077
5.000000     2180537
4.000000     2126287
              ...   
12.848666        407
12.843328        399
12.976961        381
12.709695        379
12.715033        334
Name: count, Length: 199, dtype: int64

In [ ]:
#| Step            | What it does                                  | Result                                       |
| --------------- | --------------------------------------------- | -------------------------------------------- |
| `.fit()`        | Learns regression models for imputation       | Trained imputer models                       |
| `.transform()`  | Applies learned models to fill missing values | Complete dataset with no missing values      |
| `[:10]`         | Displays first 10 rows of imputed data        | Quick preview of imputed values              |
| `df.loc[...] =` | Updates original DataFrame with imputed data  | Original DataFrame's missing values replaced |


In [42]:
df

aisle_id                       aisle  product_id  \
0                1       prepared soups salads         209   
1                1       prepared soups salads         209   
2                1       prepared soups salads         209   
3                1       prepared soups salads         209   
4                1       prepared soups salads         209   
...            ...                         ...         ...   
33819101       134  specialty wines champagnes       49661   
33819102       134  specialty wines champagnes       49661   
33819103       134  specialty wines champagnes       49661   
33819104       134  specialty wines champagnes       49661   
33819105       134  specialty wines champagnes       49661   

                 product_name  department_id department  order_id  \
0         Italian Pasta Salad             20       deli     94246   
1         Italian Pasta Salad             20       deli    192465   
2         Italian Pasta Salad             20       deli    195206   
3         Italian Pasta Salad             20       deli    227717   
4         Italian Pasta Salad             20       deli    260072   
...                       ...            ...        ...       ...   
33819101                Porto              5    alcohol   2238789   
33819102                Porto              5    alcohol   2251344   
33819103                Porto              5    alcohol   2616249   
33819104                Porto              5    alcohol   2715237   
33819105                Porto              5    alcohol   3263901   

          add_to_cart_order  reordered  user_id eval_set  order_number  \
0                         5          0   114082    prior            26   
1                         2          1   119977    prior             2   
2                        18          1     1519    prior             7   
3                         1          1   161125    prior             7   
4                        13          0    12012    prior             5   
...                     ...        ...      ...      ...           ...   
33819101                 10          1    72244    prior            19   
33819102                  5          1    72244    prior            18   
33819103                  2          0   100075    prior             8   
33819104                  1          0   135045    prior             3   
33819105                  6          1    72244    prior            15   

          order_dow  order_hour_of_day  days_since_prior_order  
0                 0                 20                     1.0  
1                 0                 16                     3.0  
2                 2                  9                     5.0  
3                 2                 11                    11.0  
4                 5                 11                    11.0  
...             ...                ...                     ...  
33819101          4                 23                     5.0  
33819102          6                 10                     9.0  
33819103          4                 17                     9.0  
33819104          6                 14                    30.0  
33819105          4                  9                    14.0  

[33819106 rows x 15 columns]

In [43]:
df.isnull().sum().sum()   #Re-checking null values after Imputation

np.int64(0)

In [44]:
df.isnull().sum()

aisle_id                  0
aisle                     0
product_id                0
product_name              0
department_id             0
department                0
order_id                  0
add_to_cart_order         0
reordered                 0
user_id                   0
eval_set                  0
order_number              0
order_dow                 0
order_hour_of_day         0
days_since_prior_order    0
dtype: int64

In [45]:
df.to_csv('No_NaN_values.csv', index = False)